apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  template:
    metadata:
       labels:
         app: app
    spec:
      containers:
        - name: app
          image: gcr.io/$PROJECT/app:current
          ports:
            - containerPort: 8080
