apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-02
spec:
  template:
    metadata:
       labels:
         app: app
         version: "02"
    spec:
      containers:
        - name: app
          image: gcr.io/$PROJECT/app:new
          ports:
            - containerPort: 8080
