apiVersion: v1
kind: Service
metadata:
  name: app-01
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app
    version: "01"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
    - "*"
  gateways:
    - app
  http:
    - route:
        - destination:
            host: app-01
